### ISSUE TITLE
Database Not Properly Modeled

### ISSUE THREAD

**Issue by rabbitmaid** [Daviangecod/Attendance-system#1]
From the image i see in the path : Students/database.jpg of your project, it seems you have two different databases.

Normally for a specified project you have
 - One database for the project
 - Many tables for different entities in the project

In other words one database is enough the contain the tables for a whole project.

**Comment by Davibytes** [comment]
Excuse me Sir , it is just the picture one of my group members sent to me ,
for the tasks she did just to show me how here database was. This doesn't
have anything to do with the project, hope you understand
